### ISSUE TITLE
UnicodeDecodeError during installation on MacOSX with Python 3.5

### ISSUE THREAD

**Issue by zopyx** [markuskiller/textblob-de#13]
```
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    namespace_packages=('zopyx', 'zopyx.txng3', 'zopyx.txng3.ext'),
  File "/opt/buildout.python/parts/opt/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/buildout.python/parts/opt/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/buildout.python/parts/opt/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/develop.py", line 133, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/pkg_resources/__init__.py", line 853, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1125, in best_match
    return self.obtain(req, installer)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1137, in obtain
    return installer(requirement)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 249, in run_setup
    raise
  File "/opt/buildout.python/parts/opt/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/opt/buildout.python/parts/opt/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 168, in save_modules
    saved_exc.resume()
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 143, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 276, in run
    return func()
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 245, in runner
    _execfile(setup_script, ns)
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/pj/5vwbn0n53d9001wfkr308p3w0000gn/T/easy_install-m9hkpidy/textblob-de-0.4.2/setup.py", line 84, in <module>
  File "/var/folders/pj/5vwbn0n53d9001wfkr308p3w0000gn/T/easy_install-m9hkpidy/textblob-de-0.4.2/setup.py", line 76, in read
  File "/Users/ajung/src/zopyx.txng3.ext/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3153: ordinal not in range(128)
```

**Comment by markuskiller** [comment]
Hi zopyx,

Thanks for the report. Did you try the recommended install process? I haven't tested ``easy_install`` for this library. 

Try: ``pip install -U textblob-de``

If the problem persists, try to change the codepage of your console window to ``utf-8``. If that doesn't help, post the error message you get when pip-installing the library.

Hope this helps and sorry for the late reply. My notifications don't seem to be working properly. I'll look into this right away.

Best wishes, Markus
