### ISSUE TITLE
ModuleNotFoundError: No module named 'textblob.translate'

### ISSUE THREAD

**Issue by mhechthz** [markuskiller/textblob-de#24]
I'm currently running Python 3.12. The Git repository of textblob-de seems to be outdated.

When I run `from textblob_de import TextBlobDE as TextBlob` I get

```
Traceback (most recent call last):
  File "C:\Micha\Programming\Python\TextProcessing\nlp_test.py", line 1, in <module>
    from textblob_de import TextBlobDE as TextBlob
  File "C:\Python312\Lib\site-packages\textblob_de\__init__.py", line 9, in <module>
    from textblob_de.blob import TextBlobDE, BlobberDE, Word, WordList, Sentence
  File "C:\Python312\Lib\site-packages\textblob_de\blob.py", line 44, in <module>
    from textblob.translate import Translator
ModuleNotFoundError: No module named 'textblob.translate'
```
So I cannot use the package.

**Comment by 7o11n3r** [comment]
Unfortunately I have the same problem here.

**Comment by matthias-fbi** [comment]
Same problem here.

**Comment by gernhard1337** [comment]
Same problem here. You can downgrade the version textblob. I found it works with textblob version 0.15.2. Downgrade version with `pip install textblob==0.15.2`
